refactor: make stages internally consistent by compiling the stageN lib with the stageN compiler, rename static libraries
The old stage1 is now stage0.5, which at least suggests that it's not an entirely consistent stage in general

diff --git a/stage0/src/Makefile.in b/stage0/src/Makefile.in
--- a/stage0/src/Makefile.in
+++ b/stage0/src/Makefile.in
@@ -1,66 +1,68 @@
 # Copyright (c) 2018 Simon Hudon. All rights reserved.
 # Released under Apache 2.0 license as described in the file LICENSE.
 # Authors: Simon Hudon, Sebastian Ullrich, Leonardo de Moura
-LEAN ?= ../bin/lean
-LEANC ?= ../bin/leanc
-LEAN_ROOT ?= .
-# Even though we copy the sources into a new directory for stage2/3, we
-# read the list of files to compile from the original directory to avoid
-# issues with stale copied files
-SRCS = $(shell cd $(LEAN_ROOT); find . -name '*.lean')
-DEPS = $(addprefix $(LEAN_ROOT)/,$(SRCS:.lean=.depend))
-OPTS = @LEAN_EXTRA_MAKE_OPTS@
-STAGE0_DIR = ../stage0
-C_OUT ?= .
-ifndef OUT
-$(error "`OUT` must be set (use cmake)")
-endif
-OBJS = $(SRCS:.lean=.olean)
-# ensure deterministic ordering
-CS_CORE=$(sort $(SRCS:.lean=.c))
+OUT = build
+OLEAN_OUT = $(OUT)
+TEMP_OUT = $(OUT)/temp
+BIN_OUT = $(OUT)/bin
+LIB_OUT = $(OUT)/lib
+BIN_NAME = $(PKG)
+STATIC_LIB_NAME = lib$(PKG).a
+LEAN_OPTS = @LEAN_EXTRA_MAKE_OPTS@
+LEANC_OPTS = -O3 -DNDEBUG
+
+SRCS = $(shell find $(PKG) -name '*.lean' || true; find $(PKG).lean 2> /dev/null)
+DEPS = $(addprefix $(TEMP_OUT)/,$(SRCS:.lean=.depend))
+export LEAN_PATH=$(PKG)=$(OLEAN_OUT)/$(PKG)
+OBJS = $(addprefix $(OLEAN_OUT)/, $(SRCS:.lean=.olean))
 
 SHELL = /usr/bin/env bash -eo pipefail
 
-.PHONY: all clean
+.PHONY: all bin lib depends
 
 all: $(OBJS)
 
+bin: $(BIN_OUT)/$(PKG)
+
+lib: $(LIB_OUT)/$(STATIC_LIB_NAME)
+
 depends: $(DEPS)
 
-%.depend: %.lean
-# use separate assignment to ensure failure propagation
-	@deps=`$(LEAN) --deps $< | python relative.py`; echo $(<:.lean=.olean): $$deps > $@
+# `lean --deps` complains if the `LEAN_PATH` doesn't point at anything
+$(OLEAN_OUT)/$(PKG) $(LIB_OUT) $(BIN_OUT):
+	@mkdir -p "$@"
 
-%.olean: %.lean %.depend $(MORE_DEPS)
+$(TEMP_OUT)/%.depend: %.lean | $(OLEAN_OUT)/$(PKG)
+	@mkdir -p "$(TEMP_OUT)/$(*D)"
+# use separate assignment to ensure failure propagation
+# convert file separators and newlines on Windows
+	@deps=`lean --deps $< | sed 's!\\\\!/!g;s/\\r//'`; echo $(OLEAN_OUT)/$(<:.lean=.olean): $$deps > $@
+
+$(OLEAN_OUT)/%.olean: %.lean $(TEMP_OUT)/%.depend $(MORE_DEPS)
 	@echo "[    ] Building $<"
-	@mkdir -p $(C_OUT)/$(*D)
-	$(LEAN) $(OPTS) --make --c="$(C_OUT)/$*.c.tmp" $<
+	@mkdir -p $(OLEAN_OUT)/$(*D)
+	lean $(LEAN_OPTS) -o "$@" --c="$(TEMP_OUT)/$*.c.tmp" $<
 # create the .c file atomically
-	mv "$(C_OUT)/$*.c.tmp" "$(C_OUT)/$*.c"
+	mv "$(TEMP_OUT)/$*.c.tmp" "$(TEMP_OUT)/$*.c"
 # make sure the .olean file is newer than the .depend file to prevent infinite make cycles
 	@touch $@
 
-$(C_OUT)/%.c: %.olean
+$(TEMP_OUT)/%.c: $(OLEAN_OUT)/%.olean
 	@
 
-$(OUT)/%.o: $(C_OUT)/%.c
+$(TEMP_OUT)/%.o: $(TEMP_OUT)/%.c
 	@echo "[    ] Building $<"
 	@mkdir -p "$(@D)"
-	$(LEANC) -c -o $@ $< $(LEANC_OPTS)
+	leanc -c -o $@ $< $(LEANC_OPTS)
 
-$(OUT)/libleanstdlib.a: $(addprefix $(OUT)/,$(SRCS:.lean=.o))
+$(BIN_OUT)/$(BIN_NAME): $(addprefix $(TEMP_OUT)/,$(SRCS:.lean=.o)) | $(BIN_OUT)
+	@echo "[    ] Linking $@"
+	leanc -o "$@" -x none $^
+
+$(LIB_OUT)/$(STATIC_LIB_NAME): $(addprefix $(TEMP_OUT)/,$(SRCS:.lean=.o)) | $(LIB_OUT)
 	@rm -f $@
 	@ar rcs $@ $^
 
-update-stage0:
-	-rm -r $(STAGE0_DIR)
-	-mkdir -p $(STAGE0_DIR)/stdlib
-	for f in $(SRCS:.lean=.c); do mkdir -p `dirname $(STAGE0_DIR)/stdlib/$$f`; cp $(C_OUT)/$$f $(STAGE0_DIR)/stdlib/$$f; done
-	echo "add_library (stage0 OBJECT $(CS_CORE))" > $(STAGE0_DIR)/stdlib/CMakeLists.txt
-# don't copy untracked crap
-	git ls-files -z . | xargs -0 -I '{}' bash -c 'mkdir -p `dirname ../stage0/src/{}` && cp {} ../stage0/src/{}'
-	-git add $(STAGE0_DIR)
-
-.PRECIOUS: %.depend $(C_OUT)/%.c
+.PRECIOUS: $(TEMP_OUT)/%.c
 
 include $(DEPS)
